# Generated by Django 2.2 on 2025-02-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
    ]
